reuse the cache entry we already have when doing rule checking
nextcloud/files_accesscontrol pull request #385
Opened 2023-07-08 12:20 UTC by icewind1991

Instead of having to re-quest the filecache for every item we have to check.

Fixes performance regression from https://github.com/nextcloud/files_accesscontrol/pull/293

2023-07-10 06:58 UTC, nickvergessen requested changes

2023-07-10 06:58 UTC, nickvergessen commented on lib/Operation.php
> +		if (!$mountPoint === false) {
???

2023-07-10 06:58 UTC, nickvergessen commented on lib/Operation.php
> +use OC\Files\View;
That's a lot of private API?

2023-07-10 06:58 UTC, nickvergessen commented on lib/Operation.php
> +	public function checkFileAccess(IStorage $storage, string $path, bool $isDir = false, $cacheEntry = null): void {
what type/data is cacheEntry?
Can we add a typehint?
It does not seem to be used/injected anywhere?

2023-07-10 11:48 UTC, icewind1991 commented on lib/Operation.php
> +		if (!$mountPoint === false) {
:see_no_evil:

2023-07-10 12:30 UTC, icewind1991 commented on lib/Operation.php
> +	public function checkFileAccess(IStorage $storage, string $path, bool $isDir = false, $cacheEntry = null): void {
Forgot to commit the other file that call this.

Added phpdoc typing

2023-07-10 13:17 UTC, icewind1991 commented on lib/Operation.php
> +use OC\Files\View;
Yeah, it's not great but it's the only way I can think to get the `Node` from the cache entry without significant overhead

2023-07-17 10:56 UTC, nickvergessen commented on lib/Operation.php
> +				'files',
CS is unhappy.

2023-07-17 10:59 UTC, nickvergessen requested changes

2023-07-17 10:59 UTC, nickvergessen commented on lib/Operation.php
> +				return new \OC\Files\Node\File($this->rootFolder, $view, $path, $info, $parent);
Integration tests fail:

```json
{
  "reqId": "VQ7FgytIC3Bb0G0joxzc",
  "level": 3,
  "time": "2023-07-10T12:33:01+00:00",
  "remoteAddr": "::1",
  "user": "test1",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/files/test1/foobar.txt",
  "message": "OC\\Files\\Node\\Node::__construct(): Argument #5 ($parent) must be of type ?OC\\Files\\Node\\Node, OC\\Files\\Node\\LazyFolder given, called in /home/runner/actions-runner/_work/files_accesscontrol/files_accesscontrol/apps/files_accesscontrol/lib/Operation.php on line 315",
  "userAgent": "GuzzleHttp/7",
  "version": "28.0.0.0",
  "exception": {
    "Exception": "TypeError",
    "Message": "OC\\Files\\Node\\Node::__construct(): Argument #5 ($parent) must be of type ?OC\\Files\\Node\\Node, OC\\Files\\Node\\LazyFolder given, called in /home/runner/actions-runner/_work/files_accesscontrol/files_accesscontrol/apps/files_accesscontrol/lib/Operation.php on line 315",
    "Code": 0,
    "Trace": [
      {
        "file": "/home/runner/actions-runner/_work/files_accesscontrol/files_accesscontrol/apps/files_accesscontrol/lib/Operation.php",
        "line": 315
…
```

2023-09-18 13:25 UTC, icewind1991 commented
rebased and updated to server changes (backport will thus need some work)

2023-09-18 13:27 UTC, icewind1991 commented
started https://github.com/nextcloud/server/pull/40478 to get a public API to make this easier for future versions

2023-09-19 12:50 UTC, nickvergessen approved these changes

2023-09-19 12:50 UTC, merged

2023-09-19 12:50 UTC, nickvergessen commented
/backport to stable27

2023-09-19 12:50 UTC, nickvergessen commented
/backport to stable26

2023-09-19 12:50 UTC, nickvergessen commented
/backport to stable25